version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
    container_name: flashcards-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules # avoid node_modules conflicts
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql_container
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=concursoPublico
      - MYSQL_PORT=3306
    networks:
      - shared_network

volumes:
  mysql-data:

networks:
  shared_network:
    external: true
