version: '3.9'

services:
  app:
    build: .
    container_name: flashcards-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@db:3306/flashcards
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: flashcards-db
    restart: always
    environment:
      MYSQL_DATABASE: flashcards
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:
